<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ApplicationIcon>..\icon.ico</ApplicationIcon>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetCraft\NetCraft.csproj" />
    <ProjectReference Include="..\NetCraft.ModLoader\NetCraft.ModLoader.csproj" />
    <ProjectReference Include="..\NetCraft.Client\NetCraft.Client.csproj" />
  </ItemGroup>

  <Import Project="..\NetCraft.KernelDeploy.targets" />

  <Target Name="KillRunningClient" BeforeTargets="BeforeBuild" Condition="'$(DesignTimeBuild)' != 'true'">
    <Exec Command="taskkill /F /IM NetCraft.ClientExe.exe /T"
          Condition="$([MSBuild]::IsOSPlatform('Windows'))"
          ContinueOnError="true"
          StandardOutputImportance="low" StandardErrorImportance="low" />
    <Exec Command="pkill -f NetCraft.ClientExe"
          Condition="!$([MSBuild]::IsOSPlatform('Windows'))"
          ContinueOnError="true"
          StandardOutputImportance="low" StandardErrorImportance="low" />
  </Target>

</Project>
