using System.Numerics;

namespace NetCraft.Gpu;

//Direction face orientation, maps to vanilla net.minecraft.core.Direction
//BakedQuad uses it to store the face normal; putBakedQuad takes UnitVector as the normal direction
public enum Direction
{
    Down, Up, North, South, West, East
}

public static class DirectionExtensions
{
    //UnitVector returns the face normal unit vector
    public static Vector3 UnitVector(this Direction d) => d switch
    {
        Direction.Down => new Vector3(0, -1, 0),
        Direction.Up => new Vector3(0, 1, 0),
        Direction.North => new Vector3(0, 0, -1),
        Direction.South => new Vector3(0, 0, 1),
        Direction.West => new Vector3(-1, 0, 0),
        Direction.East => new Vector3(1, 0, 0),
        _ => Vector3.Zero
    };
}

//BakedQuad baked quad, maps to vanilla BakedQuad record
//4 vertex positions + 4 UVs + face orientation + tintIndex; the item model is procedurally generated by CubeModel
//The normal is per-face and shared by the 4 vertices from Direction; no per-vertex normals are stored
//The PoC simplifies MaterialInfo to tintIndex + lightEmission; the full version has sprite/layer/renderType
public readonly struct BakedQuad
{
    public readonly Vector3 P0, P1, P2, P3;
    public readonly Vector2 Uv0, Uv1, Uv2, Uv3;
    public readonly Direction Direction;
    public readonly int TintIndex;
    public readonly int LightEmission;

    public BakedQuad(Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3,
        Vector2 uv0, Vector2 uv1, Vector2 uv2, Vector2 uv3,
        Direction direction, int tintIndex = -1, int lightEmission = 0)
    {
        P0 = p0; P1 = p1; P2 = p2; P3 = p3;
        Uv0 = uv0; Uv1 = uv1; Uv2 = uv2; Uv3 = uv3;
        Direction = direction;
        TintIndex = tintIndex;
        LightEmission = lightEmission;
    }

    public Vector3 Position(int i) => i switch { 0 => P0, 1 => P1, 2 => P2, _ => P3 };
    public Vector2 Uv(int i) => i switch { 0 => Uv0, 1 => Uv1, 2 => Uv2, _ => Uv3 };
    public const int VertexCount = 4;
}

//QuadInstance quad runtime instance, maps to vanilla QuadInstance
//putBakedQuad takes color and light per vertex; the PoC simplifies to one color shared by the whole quad
public sealed class QuadInstance
{
    public int Color = -1;
    public int LightCoords;
    public int OverlayCoords;

    public int GetColor(int vertex) => Color;
    //GetLightCoordsWithEmission merges the block's own emission into the blockLight field without touching sky
    //emission and the unpacked blockLight take max then re-pack, matching the vanilla face light merge semantics
    public int GetLightCoordsWithEmission(int vertex, int lightEmission)
    {
        if (lightEmission <= 0) return LightCoords;
        var blockLight = LightTexture.UnpackBlockLight(LightCoords);
        var skyLight = LightTexture.UnpackSkyLight(LightCoords);
        if (lightEmission > blockLight) blockLight = lightEmission;
        return LightTexture.PackLightCoords(blockLight, skyLight);
    }
}
