<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetCraft.Game\NetCraft.Game.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="12.1.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.3" />
    <PackageReference Include="Microsoft.Diagnostics.NETCore.Client" Version="0.2.745401" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.2.8" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="ServerGui\Assets\**" />
  </ItemGroup>

</Project>
