using System.Text;
using NetCraft.Registry;
using NetCraft.Registry.Enums;
using NetCraft.Registry.State;

namespace NetCraft.Game.World.Level.Block;

//BlockTable embedded vanilla block registry; order and state properties come from vanilla 26.2
//The table is generated by tools from vanilla sources; the order is the vanilla Blocks.java declaration order
//The registration order together with each block's state count determines the BlockState global id; the vanilla client decodes with the same ids
internal static class BlockTable
{
    private const string ResourceSuffix = ".blocks.txt";

    //Load reads blocks line by line: property definitions, default state overrides, placement category, whether they occlude light, push reaction and redstone conductor flag
    //Each line: registry name<TAB>property definitions[<TAB>extras]; extras are joined with ; from default= place= occlude= push= conductor=
    public static IEnumerable<(Identifier Id, PropertyBase[] Properties,
        IReadOnlyDictionary<string, string>? Defaults, string? Placement, bool CanOcclude,
        NetCraft.Registry.Enums.PushReaction? PushReaction, bool? RedstoneConductor)> Load()
    {
        var assembly = typeof(BlockTable).Assembly;
        //The resource name prefix follows RootNamespace, so match by suffix here to avoid syncing it when the namespace changes
        var name = Array.Find(assembly.GetManifestResourceNames(),
            n => n.EndsWith(ResourceSuffix, StringComparison.Ordinal));
        if (name is null)
            throw new InvalidOperationException(
                $"Missing embedded block table *{ResourceSuffix}, available {string.Join(",", assembly.GetManifestResourceNames())}");
        using var stream = assembly.GetManifestResourceStream(name)!;
        using var reader = new StreamReader(stream, Encoding.UTF8);
        while (reader.ReadLine() is { } line)
        {
            if (line.Length == 0 || line[0] == '#') continue;
            var fields = line.Split('\t');
            var id = Identifier.WithDefaultNamespace(fields[0]);
            //Blocks without properties still occupy an empty column so the extras field is not mistaken for the property field
            var properties = fields.Length > 1 && fields[1].Length > 0
                ? ParseProperties(id, fields[1])
                : Array.Empty<PropertyBase>();
            var extras = fields.Length > 2 ? ParseExtras(fields[2]) : default;
            yield return (id, properties, extras.Defaults, extras.Placement,
                extras.Occlude != false, extras.PushReaction, extras.RedstoneConductor);
        }
    }

    //ParseExtras parses the extras, formatted as default=name:value,name:value;place=category;occlude=false;push=destroy;conductor=false
    private static (IReadOnlyDictionary<string, string>? Defaults, string? Placement, bool? Occlude,
        NetCraft.Registry.Enums.PushReaction? PushReaction, bool? RedstoneConductor) ParseExtras(string text)
    {
        Dictionary<string, string>? defaults = null;
        string? placement = null;
        bool? occlude = null;
        NetCraft.Registry.Enums.PushReaction? pushReaction = null;
        bool? redstoneConductor = null;
        foreach (var item in text.Split(';'))
        {
            var kv = item.Split('=', 2);
            if (kv.Length != 2) continue;
            switch (kv[0])
            {
                case "place":
                    placement = kv[1];
                    break;
                case "occlude":
                    occlude = kv[1] != "false";
                    break;
                case "push":
                    //The table stores the lowercase vanilla enum member name
                    pushReaction = Enum.Parse<NetCraft.Registry.Enums.PushReaction>(kv[1]);
                    break;
                case "conductor":
                    //Only those differing from the vanilla default are listed; the vanilla default is computed from whether the collision shape is a full block
                    redstoneConductor = kv[1] != "false";
                    break;
                case "default":
                    defaults = new Dictionary<string, string>(StringComparer.Ordinal);
                    foreach (var part in kv[1].Split(','))
                    {
                        var fields = part.Split(':');
                        if (fields.Length == 2) defaults[fields[0]] = fields[1];
                    }
                    break;
            }
        }
        return (defaults, placement, occlude, pushReaction, redstoneConductor);
    }

    //ParseProperties parses one line of property definitions, formatted as name:bool|name:int:min:max|name:enum:enumName:value1,value2
    private static PropertyBase[] ParseProperties(Identifier block, string text)
    {
        var parts = text.Split('|');
        var result = new PropertyBase[parts.Length];
        for (var i = 0; i < parts.Length; i++)
            result[i] = ParseProperty(block, parts[i]);
        return result;
    }

    private static PropertyBase ParseProperty(Identifier block, string text)
    {
        var fields = text.Split(':');
        return fields[1] switch
        {
            "bool" => new BooleanProperty(fields[0]),
            "int" => new IntegerProperty(fields[0], int.Parse(fields[2]), int.Parse(fields[3])),
            "enum" => BuildEnumProperty(block, fields[0], fields[2], fields[3].Split(',')),
            _ => throw new InvalidOperationException($"{block} unknown property type {text}")
        };
    }

    //BuildEnumProperty builds an enum property from an enum name and a list of value names
    //Value names are the vanilla serialized names, the enum type is generated by the derivation script, and the value list may be only a subset of the enum
    private static PropertyBase BuildEnumProperty(Identifier block, string name, string enumName, string[] valueNames)
    {
        var enumType = BlockEnums.Resolve(enumName)
            ?? throw new InvalidOperationException($"{block} property {name} references unknown enum {enumName}");
        var values = Array.CreateInstance(enumType, valueNames.Length);
        for (var i = 0; i < valueNames.Length; i++)
            values.SetValue(Enum.Parse(enumType, valueNames[i]), i);
        var propertyType = typeof(EnumProperty<>).MakeGenericType(enumType);
        return (PropertyBase)Activator.CreateInstance(propertyType, name, values)!;
    }
}
