using System.Security.Cryptography;

namespace NetCraft.Game.Server.JsonRpc.Security;

//SecurityConfig service API key configuration, maps to vanilla net.minecraft.server.jsonrpc.security.SecurityConfig
//The key is a fixed 40-character alphanumeric; generated by GenerateSecretKey by default, or set in server.properties
public sealed record SecurityConfig(string SecretKey)
{
    private const string SecretKeyChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    private const int SecretKeyLength = 40;

    //IsValid validates the key format; anything not 40 alphanumeric characters is invalid
    public static bool IsValid(string secretKey)
    {
        if (secretKey.Length != SecretKeyLength) return false;
        foreach (var c in secretKey)
        {
            if (c is >= 'A' and <= 'Z' or >= 'a' and <= 'z' or >= '0' and <= '9') continue;
            return false;
        }
        return true;
    }

    //GenerateSecretKey generates a 40-character key using a cryptographic random source
    public static string GenerateSecretKey()
    {
        var chars = new char[SecretKeyLength];
        for (var i = 0; i < SecretKeyLength; i++)
        {
            chars[i] = SecretKeyChars[RandomNumberGenerator.GetInt32(SecretKeyChars.Length)];
        }
        return new string(chars);
    }
}
