//SynchronizedTagData the tag data of synchronized registries under vanilla 26.2 data/minecraft/tags
//Extracted from the vanilla jar and resolved into registry int ids (indexed against the same lexicographic entry list as SynchronizedRegistryData)
//#tag references are recursively expanded; required:false references not in the registry are skipped, and an empty-result tag is still sent (client binding requires the tag to exist)
//biome is not included here; the server registry only has plains, whose elements have no tag references
namespace NetCraft.Network.Protocol.Configuration;

public static class SynchronizedTagData
{
    //All each element is (registry id, tag name, entry int id array), sorted by registry + tag name
    public static readonly (string Registry, string Tag, int[] Ids)[] All =
    {
        ("minecraft:banner_pattern", "no_item_required", new[] { 26,27,28,29,31,38,35,37,32,36,34,33,25,5,30,39,40,41,42,7,10,9,8,3,23,19,17,20,18,1,14,15 }),
        ("minecraft:banner_pattern", "pattern_item/bordure_indented", new[] { 6 }),
        ("minecraft:banner_pattern", "pattern_item/creeper", new[] { 4 }),
        ("minecraft:banner_pattern", "pattern_item/field_masoned", new[] { 2 }),
        ("minecraft:banner_pattern", "pattern_item/flow", new[] { 11 }),
        ("minecraft:banner_pattern", "pattern_item/flower", new[] { 12 }),
        ("minecraft:banner_pattern", "pattern_item/globe", new[] { 13 }),
        ("minecraft:banner_pattern", "pattern_item/guster", new[] { 16 }),
        ("minecraft:banner_pattern", "pattern_item/mojang", new[] { 21 }),
        ("minecraft:banner_pattern", "pattern_item/piglin", new[] { 22 }),
        ("minecraft:banner_pattern", "pattern_item/skull", new[] { 24 }),
        ("minecraft:damage_type", "always_hurts_ender_dragons", new int[] { }),
        ("minecraft:damage_type", "always_kills_armor_stands", new[] { 0,46,14,50,48 }),
        ("minecraft:damage_type", "always_most_significant_fall", new[] { 32 }),
        ("minecraft:damage_type", "always_triggers_silverfish", new[] { 27 }),
        ("minecraft:damage_type", "avoids_guardian_thorns", new[] { 27,44 }),
        ("minecraft:damage_type", "burn_from_stepping", new[] { 3,20,42 }),
        ("minecraft:damage_type", "burns_armor_stands", new[] { 31 }),
        ("minecraft:damage_type", "bypasses_armor", new[] { 31,22,4,6,16,18,49,5,40,10,8,17,39,27,23,32,19,36,33 }),
        ("minecraft:damage_type", "bypasses_effects", new[] { 40 }),
        ("minecraft:damage_type", "bypasses_enchantments", new[] { 36 }),
        ("minecraft:damage_type", "bypasses_invulnerability", new[] { 32,19 }),
        ("minecraft:damage_type", "bypasses_resistance", new[] { 32,19 }),
        ("minecraft:damage_type", "bypasses_shield", new[] { 2,3,7,11,13,20,42,21,24,25,43 }),
        ("minecraft:damage_type", "bypasses_wolf_armor", new[] { 4,6,7,17,22,23,27,33,40,44,49 }),
        ("minecraft:damage_type", "can_break_armor_stand", new[] { 35 }),
        ("minecraft:damage_type", "damages_helmet", new[] { 11,12,13 }),
        ("minecraft:damage_type", "ignites_armor_stands", new[] { 21,3 }),
        ("minecraft:damage_type", "is_drowning", new[] { 6 }),
        ("minecraft:damage_type", "is_explosion", new[] { 15,9,35,1 }),
        ("minecraft:damage_type", "is_fall", new[] { 10,8,39 }),
        ("minecraft:damage_type", "is_fire", new[] { 21,3,31,24,20,42,47,14 }),
        ("minecraft:damage_type", "is_freezing", new[] { 17 }),
        ("minecraft:damage_type", "is_lightning", new[] { 25 }),
        ("minecraft:damage_type", "is_player_attack", new[] { 34,37,26 }),
        ("minecraft:damage_type", "is_projectile", new[] { 0,46,30,47,14,50,45,48 }),
        ("minecraft:damage_type", "mace_smash", new[] { 26 }),
        ("minecraft:damage_type", "no_anger", new[] { 29 }),
        ("minecraft:damage_type", "no_impact", new[] { 6 }),
        ("minecraft:damage_type", "no_knockback", new[] { 9,35,1,21,25,31,24,20,42,22,4,6,40,2,10,8,16,32,18,27,49,5,7,43,17,39,33,19,3,37 }),
        ("minecraft:damage_type", "panic_causes", new[] { 0,5,9,14,15,23,27,28,30,35,36,41,45,46,47,48,49,50 }),
        ("minecraft:damage_type", "panic_environmental_causes", new[] { 2,17,20,42,21,24,25,31 }),
        ("minecraft:damage_type", "sulfur_cube_with_block_immune_to", new[] { 0,2,7,10,11,12,13,17,26,20,28,29,30,34,37,38,39,41,42,43,45,46,48 }),
        ("minecraft:damage_type", "witch_resistant_to", new[] { 27,23,36,44 }),
        ("minecraft:damage_type", "wither_immune_to", new[] { 6 }),
        ("minecraft:dialog", "pause_screen_additions", new int[] { }),
        ("minecraft:dialog", "quick_actions", new int[] { }),
        ("minecraft:enchantment", "curse", new[] { 2,41 }),
        ("minecraft:enchantment", "double_trade_price", new int[] { }),
        ("minecraft:enchantment", "exclusive_set/armor", new[] { 28,3,11,27 }),
        ("minecraft:enchantment", "exclusive_set/boots", new[] { 14,7 }),
        ("minecraft:enchantment", "exclusive_set/bow", new[] { 16,23 }),
        ("minecraft:enchantment", "exclusive_set/crossbow", new[] { 24,25 }),
        ("minecraft:enchantment", "exclusive_set/damage", new[] { 33,35,1,15,6,4 }),
        ("minecraft:enchantment", "exclusive_set/mining", new[] { 13,34 }),
        ("minecraft:enchantment", "exclusive_set/riptide", new[] { 19,5 }),
        ("minecraft:enchantment", "in_enchanting_table", new int[] { }),
        ("minecraft:enchantment", "non_treasure", new[] { 28,11,9,3,27,31,0,39,7,33,35,1,17,10,18,37,8,34,40,13,26,29,12,16,20,22,19,15,32,5,24,30,25,6,4,21 }),
        ("minecraft:enchantment", "on_mob_spawn_equipment", new int[] { }),
        ("minecraft:enchantment", "on_random_loot", new[] { 2,41,14,23 }),
        ("minecraft:enchantment", "on_traded_equipment", new int[] { }),
        ("minecraft:enchantment", "prevents_bee_spawns_when_mining", new[] { 34 }),
        ("minecraft:enchantment", "prevents_decorated_pot_shattering", new[] { 34 }),
        ("minecraft:enchantment", "prevents_ice_melting", new[] { 34 }),
        ("minecraft:enchantment", "prevents_infested_spawns", new[] { 34 }),
        ("minecraft:enchantment", "smelts_loot", new[] { 10 }),
        ("minecraft:enchantment", "tooltip_order", new[] { 2,41,32,5,42,14,21,33,35,1,15,26,6,4,25,37,24,10,12,17,29,28,3,11,27,9,13,18,34,20,8,30,22,31,0,36,38,7,39,19,40,16,23 }),
        ("minecraft:enchantment", "tradeable", new[] { 2,41,14,23 }),
        ("minecraft:enchantment", "treasure", new[] { 2,41,38,36,14,23,42 }),
        ("minecraft:instrument", "goat_horns", new int[] { }),
        ("minecraft:instrument", "regular_goat_horns", new[] { 4,6,5,3 }),
        ("minecraft:instrument", "screaming_goat_horns", new[] { 0,1,7,2 }),
        ("minecraft:painting_variant", "placeable", new[] { 24,1,0,2,5,32,47,35,12,37,42,13,46,22,26,8,40,45,39,50,19,33,31,7,38,15,4,23,27,36,44,3,6,9,10,11,17,18,20,25,28,29,30,34,41,43,14 }),
        ("minecraft:timeline", "in_end", new int[] { }),
        ("minecraft:timeline", "in_nether", new int[] { }),
        ("minecraft:timeline", "in_overworld", new[] { 0,2,1 }),
        ("minecraft:timeline", "universal", new[] { 3 }),
    };
}
