server-port=25565
max-players=20
level-name=world
gamemode=survival
difficulty=easy
online-mode=true
pvp=true
view-distance=10
simulation-distance=10
allow-flight=false
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
white-list=false
generate-structures=true
allow-nether=true
level-seed=
level-type=default
max-world-size=29999984
motd=A Minecraft Server
enable-rcon=false
enable-query=false
rcon.port=25575
rcon.password=
broadcast-rcon-to-ops=true
query.port=25565
server-ip=
function-permission-level=2
op-permission-level=4
player-idle-timeout=0
nc-debug-commands=false
nc-language=en_us
