<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetCraft.Game\NetCraft.Game.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NetCraft.Test" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DnsClient" Version="1.8.0" />
    <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Windowing.Glfw" Version="2.23.0" />
    <PackageReference Include="Veldrid.SPIRV" Version="1.0.15" />
    <PackageReference Include="StbTrueTypeSharp" Version="1.26.3" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Blaze3d\Shaders\**\*.glsl" />
  </ItemGroup>

</Project>
