<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Windowing.Glfw" Version="2.23.0" />
    <PackageReference Include="Veldrid.SPIRV" Version="1.0.15" />
    <PackageReference Include="StbTrueTypeSharp" Version="1.26.3" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Shaders\**\*.glsl" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NetCraft.Test" />
  </ItemGroup>

</Project>
