using NetCraft.Registry.Enums;

namespace NetCraft.Registry.State;

//BlockStateProperties common state property constants, maps to the vanilla class of the same name
//Property names and value order must match exactly the ones generated by blocks.txt for placeholder blocks, or global BlockState ids will be misaligned
//Value order follows vanilla's actual iteration order; vanilla HORIZONTAL_FACING passes Direction.Plane.HORIZONTAL, whose set iterates by enum index in 26.2
//So the four horizontal directions are north south west east rather than NORTH EAST SOUTH WEST; properties given all six directions explicitly still follow call order
public static class BlockStateProperties
{
    //Horizontal facing; levers, buttons, repeaters, comparators and wall torches only accept horizontal directions
    public static readonly EnumProperty<Direction> HorizontalFacing = new("facing", new[]
    {
        Direction.north, Direction.south, Direction.west, Direction.east,
    });

    //Attach face; levers and buttons use floor/wall/ceiling, maps to vanilla ATTACH_FACE
    public static readonly EnumProperty<AttachFace> AttachFaceProperty = new("face", new[]
    {
        AttachFace.floor, AttachFace.wall, AttachFace.ceiling,
    });

    //Whether powered
    public static readonly BooleanProperty Powered = new("powered");

    //Signal strength 0-15, used by weighted pressure plates and redstone wire
    public static readonly IntegerProperty Power = new("power", 0, 15);

    //Whether lit, used by redstone torches
    public static readonly BooleanProperty Lit = new("lit");

    //Whether a tripwire hook and tripwire are connected, maps to vanilla ATTACHED
    public static readonly BooleanProperty Attached = new("attached");

    //Whether the tripwire is disarmed; once cut it no longer triggers when stepped on, maps to vanilla DISARMED
    public static readonly BooleanProperty Disarmed = new("disarmed");

    //Whether the daylight detector outputs inverted; when inverted it signals at night and not during the day, maps to vanilla INVERTED
    public static readonly BooleanProperty Inverted = new("inverted");

    //Note block pitch 0-24 covering two octaves, maps to vanilla NOTE
    public static readonly IntegerProperty Note = new("note", 0, 24);

    //Note block instrument; value order follows blocks.txt and the NoteBlockInstrument declaration order
    public static readonly EnumProperty<NoteBlockInstrument> NoteBlockInstrumentProperty =
        new("instrument", new[]
        {
            NoteBlockInstrument.harp, NoteBlockInstrument.basedrum, NoteBlockInstrument.snare,
            NoteBlockInstrument.hat, NoteBlockInstrument.bass, NoteBlockInstrument.flute,
            NoteBlockInstrument.bell, NoteBlockInstrument.guitar, NoteBlockInstrument.chime,
            NoteBlockInstrument.xylophone, NoteBlockInstrument.iron_xylophone, NoteBlockInstrument.cow_bell,
            NoteBlockInstrument.didgeridoo, NoteBlockInstrument.bit, NoteBlockInstrument.banjo,
            NoteBlockInstrument.pling, NoteBlockInstrument.trumpet, NoteBlockInstrument.trumpet_exposed,
            NoteBlockInstrument.trumpet_oxidized, NoteBlockInstrument.trumpet_weathered,
            NoteBlockInstrument.zombie, NoteBlockInstrument.skeleton, NoteBlockInstrument.creeper,
            NoteBlockInstrument.dragon, NoteBlockInstrument.wither_skeleton, NoteBlockInstrument.piglin,
            NoteBlockInstrument.custom_head,
        });

    //Whether each of the four tripwire directions connects to an adjacent tripwire or tripwire hook, maps to vanilla NORTH/EAST/SOUTH/WEST
    //Redstone wire also has a property named north but that is a three-state enum; same name, different type, independent of each other
    public static readonly BooleanProperty NorthConnected = new("north");
    public static readonly BooleanProperty EastConnected = new("east");
    public static readonly BooleanProperty SouthConnected = new("south");
    public static readonly BooleanProperty WestConnected = new("west");

    //Rail shape, six straight variants; value order follows blocks.txt from north_south to ascending_south
    //Regular rails carry four additional curves, maps to vanilla RAIL_SHAPE_STRAIGHT and RAIL_SHAPE
    public static readonly EnumProperty<RailShape> RailShapeStraight = new("shape", new[]
    {
        RailShape.north_south, RailShape.east_west, RailShape.ascending_east,
        RailShape.ascending_west, RailShape.ascending_north, RailShape.ascending_south,
    });

    public static readonly EnumProperty<RailShape> RailShapeAll = new("shape", new[]
    {
        RailShape.north_south, RailShape.east_west, RailShape.ascending_east,
        RailShape.ascending_west, RailShape.ascending_north, RailShape.ascending_south,
        RailShape.south_east, RailShape.south_west, RailShape.north_west, RailShape.north_east,
    });

    //Repeater delay level 1-4, each level two ticks, maps to vanilla DELAY
    public static readonly IntegerProperty Delay = new("delay", 1, 4);

    //Whether the repeater is locked by a side input; it does not toggle while locked, maps to vanilla LOCKED
    public static readonly BooleanProperty Locked = new("locked");

    //Comparator mode; value order follows blocks.txt as compare,subtract
    public static readonly EnumProperty<ComparatorMode> ComparatorModeProperty = new("mode", new[]
    {
        ComparatorMode.compare, ComparatorMode.subtract,
    });

    //Redstone wire connection state for each of the four directions; value order follows blocks.txt as up,side,none
    //One property instance per direction, so the redstone wire state count is 3^4 times 16 power levels
    //The value array must be declared before the four properties because static fields initialize in textual order
    private static readonly RedstoneSide[] RedstoneSideValues =
    {
        RedstoneSide.up, RedstoneSide.side, RedstoneSide.none,
    };

    public static readonly EnumProperty<RedstoneSide> NorthRedstone = new("north", RedstoneSideValues);
    public static readonly EnumProperty<RedstoneSide> EastRedstone = new("east", RedstoneSideValues);
    public static readonly EnumProperty<RedstoneSide> SouthRedstone = new("south", RedstoneSideValues);
    public static readonly EnumProperty<RedstoneSide> WestRedstone = new("west", RedstoneSideValues);

    //Six-way facing used by blocks like observers that include UP/DOWN; value order follows blocks.txt as north,east,south,west,up,down
    //Note this is not the same instance as the four-way HorizontalFacing and must not be interchanged
    public static readonly EnumProperty<Direction> FacingProperty = new("facing", new[]
    {
        Direction.north, Direction.east, Direction.south, Direction.west,
        Direction.up, Direction.down,
    });

    //Axis used by logs and pillar blocks; value order follows blocks.txt as x,y,z
    public static readonly EnumProperty<Axis> AxisProperty = new("axis", new[]
    {
        Axis.x, Axis.y, Axis.z,
    });

    //tip the end-segment marker for hanging blocks; hanging moss and the like use it to distinguish the tip shape, maps to vanilla TIP
    public static readonly BooleanProperty Tip = new("tip");

    //eye whether the end portal frame has an eye inserted, maps to vanilla EYE
    public static readonly BooleanProperty Eye = new("eye");

    //candles the number of candles in a candle block, 1-4, maps to vanilla CANDLES
    public static readonly IntegerProperty Candles = new("candles", 1, 4);

    //hanging whether a lantern-like block hangs below another block, maps to vanilla HANGING
    public static readonly BooleanProperty Hanging = new("hanging");

    //layers snow thickness 1-8, maps to vanilla LAYERS
    public static readonly IntegerProperty Layers = new("layers", 1, 8);

    //bites the number of bites taken from a cake, 0-6, maps to vanilla BITES
    public static readonly IntegerProperty Bites = new("bites", 0, 6);

    //age crop maturity; ranges differ per crop, and the same name and type is unique on each block, so they do not conflict
    public static readonly IntegerProperty Age1 = new("age", 0, 1);
    public static readonly IntegerProperty Age3 = new("age", 0, 3);
    public static readonly IntegerProperty Age7 = new("age", 0, 7);

    //hatch turtle egg hatching progress 0-2, maps to vanilla HATCH
    public static readonly IntegerProperty Hatch = new("hatch", 0, 2);

    //eggs number of turtle eggs 1-4, maps to vanilla EGGS
    public static readonly IntegerProperty Eggs = new("eggs", 1, 4);

    //level light block brightness 0-15, maps to vanilla LightBlock's LEVEL
    public static readonly IntegerProperty Level15 = new("level", 0, 15);

    //level composter fill level 0-8, full at level eight, maps to vanilla COMPOSTER's LEVEL
    public static readonly IntegerProperty LevelComposter = new("level", 0, 8);

    //distance scaffolding distance to its support 0-7, smaller is more stable, maps to vanilla STABILITY_DISTANCE
    public static readonly IntegerProperty StabilityDistance = new("distance", 0, 7);

    //bottom whether the scaffolding rests on the block below, maps to vanilla BOTTOM
    public static readonly BooleanProperty Bottom = new("bottom");

    //stage bamboo growth stage 0-1, maps to vanilla STAGE
    public static readonly IntegerProperty Stage = new("stage", 0, 1);

    //leaves bamboo leaf shape; value order follows blocks.txt as none,small,large
    public static readonly EnumProperty<BambooLeaves> BambooLeavesProperty = new("leaves", new[]
    {
        BambooLeaves.none, BambooLeaves.small, BambooLeaves.large,
    });

    //short whether the piston head is retracted, maps to vanilla SHORT
    public static readonly BooleanProperty Short = new("short");

    //extended whether the piston is extended, maps to vanilla EXTENDED
    public static readonly BooleanProperty Extended = new("extended");

    //triggered whether the dispenser or dropper has been triggered by a signal, maps to vanilla TRIGGERED
    //Set on the rising edge and scheduled for a tick, cleared on the falling edge; the flag prevents a single activation from firing twice
    public static readonly BooleanProperty Triggered = new("triggered");

    //type whether the piston head is normal or sticky; value order follows blocks.txt as normal,sticky
    public static readonly EnumProperty<PistonType> PistonTypeProperty = new("type", new[]
    {
        PistonType.normal, PistonType.sticky,
    });

    //waterlogged whether the block cell contains water, maps to vanilla WATERLOGGED
    public static readonly BooleanProperty Waterlogged = new("waterlogged");

    //open whether a door, trapdoor or fence gate is open, maps to vanilla OPEN
    public static readonly BooleanProperty Open = new("open");

    //half trapdoor split into top and bottom; value order follows blocks.txt as top,bottom, maps to vanilla HALF
    //The Enums namespace's Half has the same name as System.Half, so the fully qualified name is used here
    public static readonly EnumProperty<NetCraft.Registry.Enums.Half> HalfProperty = new("half", new[]
    {
        NetCraft.Registry.Enums.Half.top, NetCraft.Registry.Enums.Half.bottom,
    });

    //in_wall whether the fence gate is wedged between walls; when wedged the gate is lowered, maps to vanilla IN_WALL
    public static readonly BooleanProperty InWall = new("in_wall");

    //half door split into upper and lower cells; value order follows blocks.txt as upper,lower, maps to vanilla DOUBLE_BLOCK_HALF
    public static readonly EnumProperty<DoubleBlockHalf> DoubleBlockHalfProperty = new("half", new[]
    {
        DoubleBlockHalf.upper, DoubleBlockHalf.lower,
    });

    //hinge which side the door hinge is on; value order follows blocks.txt as left,right, maps to vanilla DOOR_HINGE
    public static readonly EnumProperty<DoorHingeSide> DoorHinge = new("hinge", new[]
    {
        DoorHingeSide.left, DoorHingeSide.right,
    });

    //pickles how many sea pickles grow in one cell, 1-4, maps to vanilla PICKLES
    public static readonly IntegerProperty Pickles = new("pickles", 1, 4);

    //type slab shape; value order follows blocks.txt as top,bottom,double
    public static readonly EnumProperty<SlabType> SlabTypeProperty = new("type", new[]
    {
        SlabType.top, SlabType.bottom, SlabType.@double,
    });

    //type chest shape, single chest or left/right half of a double chest; value order follows blocks.txt as single,left,right
    public static readonly EnumProperty<ChestType> ChestTypeProperty = new("type", new[]
    {
        ChestType.single, ChestType.left, ChestType.right,
    });
}

//RedstoneSideExtensions helpers for redstone wire connection checks, maps to vanilla RedstoneSide.isConnected
public static class RedstoneSideExtensions
{
    //IsConnected anything other than none counts as connected
    public static bool IsConnected(this RedstoneSide side) => side != RedstoneSide.none;
}
