using NetCraft.Codec;
using NetCraft.Registry;
using NetCraft.Registry.Codec;

namespace NetCraft.Game.World.Level.LevelGen;

//MultiNoisePreset multi-noise parameter list preset, maps to vanilla MultiNoiseBiomeSourceParameterList.Preset
//Only supplies the preset identity and the parameter list generation entry point; the list contents are not ported
public sealed class MultiNoisePreset
{
    public Identifier Id { get; }

    private MultiNoisePreset(Identifier id) => Id = id;

    //Overworld/Nether built-in presets, maps to vanilla OVERWORLD/NETHER
    public static readonly MultiNoisePreset Overworld = new(Identifier.WithDefaultNamespace("overworld"));
    public static readonly MultiNoisePreset Nether = new(Identifier.WithDefaultNamespace("nether"));

    private static readonly MultiNoisePreset[] All = { Overworld, Nether };

    //ById looks up a preset by registry name, returns null when not found
    public static MultiNoisePreset? ById(Identifier id)
    {
        foreach (var preset in All)
            if (preset.Id == id) return preset;
        return null;
    }

    //CreateEntries builds the parameter list entries
    //lookup resolves a biome ResourceKey into a Holder, matching vanilla passing a HolderGetter into the preset provider
    //Overworld is expanded on the spot through OverworldBiomeBuilder; Nether is the 5 hard-coded entries
    public IReadOnlyList<(Climate.ParameterPoint Point, Holder<Biome> Biome)> CreateEntries(
        Func<ResourceKey<Biome>, Holder<Biome>> lookup)
    {
        var entries = new List<(Climate.ParameterPoint, Holder<Biome>)>();
        if (Id == Overworld.Id)
        {
            new OverworldBiomeBuilder().AddBiomes(e => entries.Add((e.Point, lookup(e.Biome))));
        }
        else if (Id == Nether.Id)
        {
            foreach (var (point, biome) in OverworldBiomeBuilder.NetherBiomes())
                entries.Add((point, lookup(biome)));
        }
        return entries;
    }

    //Codec encodes by registry name, maps to vanilla Preset.CODEC
    public static readonly Codec<MultiNoisePreset> Codec = IdentifierCodec.Instance.ComapFlatMap(
        id => ById(id) is { } preset
            ? DataResult<MultiNoisePreset>.Success(preset)
            : DataResult<MultiNoisePreset>.Error(() => $"Unknown preset: {id}"),
        preset => preset.Id);
}

//MultiNoiseBiomeSourceParameterListCodec parameter list codec, maps to vanilla DIRECT_CODEC
//JSON has only the single preset field; the biome list is generated by the preset itself
public sealed class MultiNoiseBiomeSourceParameterListCodec : AbstractMapCodec<MultiNoiseBiomeSourceParameterList>
{
    public static readonly MultiNoiseBiomeSourceParameterListCodec Instance = new();

    public override DataResult<MultiNoiseBiomeSourceParameterList> Decode<U>(DynamicOps<U> ops, MapLike<U> input)
    {
        var presetTag = input.Get("preset");
        if (!presetTag.IsPresent)
            return DataResult<MultiNoiseBiomeSourceParameterList>.Error(() => "Missing key preset");
        var presetResult = MultiNoisePreset.Codec.Parse(ops, presetTag.Get());
        if (!presetResult.Result().IsPresent)
            return DataResult<MultiNoiseBiomeSourceParameterList>.Error(() => "Invalid preset for MultiNoiseBiomeSourceParameterList");
        var preset = presetResult.GetOrThrow();

        //The parameter list is expanded on the spot by the preset; biomes are resolved through the BIOME registry by ResourceKey
        var biomes = (ops as RegistryOps<U>)?.GetRegistry(Registries.BIOME) ?? BuiltInRegistries.BIOME;
        return DataResult<MultiNoiseBiomeSourceParameterList>.Success(
            new MultiNoiseBiomeSourceParameterList(preset, preset.CreateEntries(key => Lookup(biomes, key))));
    }

    //Lookup resolves a biome by ResourceKey; a missing one throws and the loader records it as that element's error
    //BIOME is a registry with a default value, so GetValue falls back to the default biome for unregistered keys; ContainsKey must come first or biomes silently mix up
    private static Holder<Biome> Lookup(Registry<Biome> biomes, ResourceKey<Biome> key)
        => biomes.ContainsKey(key.Identifier) && biomes.GetValue(key.Identifier) is { } biome
            ? Holder<Biome>.Direct(biome)
            : throw new InvalidOperationException($"Unknown biome: {key.Identifier}");

    public override RecordBuilder<U> EncodeTo<U>(DynamicOps<U> ops, MultiNoiseBiomeSourceParameterList value,
        RecordBuilder<U> builder)
    {
        if (value.Preset is null)
            return builder.Add("preset", DataResult<U>.Error(() => "MultiNoiseBiomeSourceParameterList has no preset").GetOrThrow());
        builder.Add("preset", ops.CreateString(value.Preset.Id.ToString()));
        return builder;
    }
}
