//此文件由 __gen_il_opcodes.py 从 opcode.def 生成 不要手改
//来源 dotnet/runtime 10.0.9 src/coreclr/inc/opcode.def  MIT

use super::OperandType;

//OpCode 一条指令的静态信息
#[derive(Clone, Copy)]
pub struct OpCode {
    pub name: &'static str,
    pub operand: OperandType,
    //opcode 自身占几个字节 单字节指令是 1 双字节(带 0xFE 前缀)是 2
    pub size: u8,
}

//SINGLE_BYTE 首字节不是 0xFE 的指令
pub static SINGLE_BYTE: [Option<OpCode>; 256] = [
    Some(OpCode { name: "nop", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "break", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldarg.0", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldarg.1", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldarg.2", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldarg.3", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldloc.0", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldloc.1", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldloc.2", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldloc.3", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stloc.0", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stloc.1", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stloc.2", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stloc.3", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldarg.s", operand: OperandType::ShortInlineVar, size: 1 }),
    Some(OpCode { name: "ldarga.s", operand: OperandType::ShortInlineVar, size: 1 }),
    Some(OpCode { name: "starg.s", operand: OperandType::ShortInlineVar, size: 1 }),
    Some(OpCode { name: "ldloc.s", operand: OperandType::ShortInlineVar, size: 1 }),
    Some(OpCode { name: "ldloca.s", operand: OperandType::ShortInlineVar, size: 1 }),
    Some(OpCode { name: "stloc.s", operand: OperandType::ShortInlineVar, size: 1 }),
    Some(OpCode { name: "ldnull", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldc.i4.m1", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldc.i4.0", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldc.i4.1", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldc.i4.2", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldc.i4.3", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldc.i4.4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldc.i4.5", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldc.i4.6", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldc.i4.7", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldc.i4.8", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldc.i4.s", operand: OperandType::ShortInlineI, size: 1 }),
    Some(OpCode { name: "ldc.i4", operand: OperandType::InlineI, size: 1 }),
    Some(OpCode { name: "ldc.i8", operand: OperandType::InlineI8, size: 1 }),
    Some(OpCode { name: "ldc.r4", operand: OperandType::ShortInlineR, size: 1 }),
    Some(OpCode { name: "ldc.r8", operand: OperandType::InlineR, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "dup", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "pop", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "jmp", operand: OperandType::InlineMethod, size: 1 }),
    Some(OpCode { name: "call", operand: OperandType::InlineMethod, size: 1 }),
    Some(OpCode { name: "calli", operand: OperandType::InlineSig, size: 1 }),
    Some(OpCode { name: "ret", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "br.s", operand: OperandType::ShortInlineBrTarget, size: 1 }),
    Some(OpCode { name: "brfalse.s", operand: OperandType::ShortInlineBrTarget, size: 1 }),
    Some(OpCode { name: "brtrue.s", operand: OperandType::ShortInlineBrTarget, size: 1 }),
    Some(OpCode { name: "beq.s", operand: OperandType::ShortInlineBrTarget, size: 1 }),
    Some(OpCode { name: "bge.s", operand: OperandType::ShortInlineBrTarget, size: 1 }),
    Some(OpCode { name: "bgt.s", operand: OperandType::ShortInlineBrTarget, size: 1 }),
    Some(OpCode { name: "ble.s", operand: OperandType::ShortInlineBrTarget, size: 1 }),
    Some(OpCode { name: "blt.s", operand: OperandType::ShortInlineBrTarget, size: 1 }),
    Some(OpCode { name: "bne.un.s", operand: OperandType::ShortInlineBrTarget, size: 1 }),
    Some(OpCode { name: "bge.un.s", operand: OperandType::ShortInlineBrTarget, size: 1 }),
    Some(OpCode { name: "bgt.un.s", operand: OperandType::ShortInlineBrTarget, size: 1 }),
    Some(OpCode { name: "ble.un.s", operand: OperandType::ShortInlineBrTarget, size: 1 }),
    Some(OpCode { name: "blt.un.s", operand: OperandType::ShortInlineBrTarget, size: 1 }),
    Some(OpCode { name: "br", operand: OperandType::InlineBrTarget, size: 1 }),
    Some(OpCode { name: "brfalse", operand: OperandType::InlineBrTarget, size: 1 }),
    Some(OpCode { name: "brtrue", operand: OperandType::InlineBrTarget, size: 1 }),
    Some(OpCode { name: "beq", operand: OperandType::InlineBrTarget, size: 1 }),
    Some(OpCode { name: "bge", operand: OperandType::InlineBrTarget, size: 1 }),
    Some(OpCode { name: "bgt", operand: OperandType::InlineBrTarget, size: 1 }),
    Some(OpCode { name: "ble", operand: OperandType::InlineBrTarget, size: 1 }),
    Some(OpCode { name: "blt", operand: OperandType::InlineBrTarget, size: 1 }),
    Some(OpCode { name: "bne.un", operand: OperandType::InlineBrTarget, size: 1 }),
    Some(OpCode { name: "bge.un", operand: OperandType::InlineBrTarget, size: 1 }),
    Some(OpCode { name: "bgt.un", operand: OperandType::InlineBrTarget, size: 1 }),
    Some(OpCode { name: "ble.un", operand: OperandType::InlineBrTarget, size: 1 }),
    Some(OpCode { name: "blt.un", operand: OperandType::InlineBrTarget, size: 1 }),
    Some(OpCode { name: "switch", operand: OperandType::InlineSwitch, size: 1 }),
    Some(OpCode { name: "ldind.i1", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldind.u1", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldind.i2", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldind.u2", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldind.i4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldind.u4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldind.i8", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldind.i", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldind.r4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldind.r8", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldind.ref", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stind.ref", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stind.i1", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stind.i2", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stind.i4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stind.i8", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stind.r4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stind.r8", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "add", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "sub", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "mul", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "div", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "div.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "rem", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "rem.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "and", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "or", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "xor", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "shl", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "shr", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "shr.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "neg", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "not", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.i1", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.i2", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.i4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.i8", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.r4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.r8", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.u4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.u8", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "callvirt", operand: OperandType::InlineMethod, size: 1 }),
    Some(OpCode { name: "cpobj", operand: OperandType::InlineType, size: 1 }),
    Some(OpCode { name: "ldobj", operand: OperandType::InlineType, size: 1 }),
    Some(OpCode { name: "ldstr", operand: OperandType::InlineString, size: 1 }),
    Some(OpCode { name: "newobj", operand: OperandType::InlineMethod, size: 1 }),
    Some(OpCode { name: "castclass", operand: OperandType::InlineType, size: 1 }),
    Some(OpCode { name: "isinst", operand: OperandType::InlineType, size: 1 }),
    Some(OpCode { name: "conv.r.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unbox", operand: OperandType::InlineType, size: 1 }),
    Some(OpCode { name: "throw", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldfld", operand: OperandType::InlineField, size: 1 }),
    Some(OpCode { name: "ldflda", operand: OperandType::InlineField, size: 1 }),
    Some(OpCode { name: "stfld", operand: OperandType::InlineField, size: 1 }),
    Some(OpCode { name: "ldsfld", operand: OperandType::InlineField, size: 1 }),
    Some(OpCode { name: "ldsflda", operand: OperandType::InlineField, size: 1 }),
    Some(OpCode { name: "stsfld", operand: OperandType::InlineField, size: 1 }),
    Some(OpCode { name: "stobj", operand: OperandType::InlineType, size: 1 }),
    Some(OpCode { name: "conv.ovf.i1.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.i2.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.i4.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.i8.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.u1.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.u2.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.u4.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.u8.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.i.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.u.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "box", operand: OperandType::InlineType, size: 1 }),
    Some(OpCode { name: "newarr", operand: OperandType::InlineType, size: 1 }),
    Some(OpCode { name: "ldlen", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldelema", operand: OperandType::InlineType, size: 1 }),
    Some(OpCode { name: "ldelem.i1", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldelem.u1", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldelem.i2", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldelem.u2", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldelem.i4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldelem.u4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldelem.i8", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldelem.i", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldelem.r4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldelem.r8", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldelem.ref", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stelem.i", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stelem.i1", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stelem.i2", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stelem.i4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stelem.i8", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stelem.r4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stelem.r8", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "stelem.ref", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldelem", operand: OperandType::InlineType, size: 1 }),
    Some(OpCode { name: "stelem", operand: OperandType::InlineType, size: 1 }),
    Some(OpCode { name: "unbox.any", operand: OperandType::InlineType, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.i1", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.u1", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.i2", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.u2", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.i4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.u4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.i8", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.u8", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "refanyval", operand: OperandType::InlineType, size: 1 }),
    Some(OpCode { name: "ckfinite", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "mkrefany", operand: OperandType::InlineType, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "ldtoken", operand: OperandType::InlineTok, size: 1 }),
    Some(OpCode { name: "conv.u2", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.u1", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.i", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.i", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.ovf.u", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "add.ovf", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "add.ovf.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "mul.ovf", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "mul.ovf.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "sub.ovf", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "sub.ovf.un", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "endfinally", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "leave", operand: OperandType::InlineBrTarget, size: 1 }),
    Some(OpCode { name: "leave.s", operand: OperandType::ShortInlineBrTarget, size: 1 }),
    Some(OpCode { name: "stind.i", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "conv.u", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "prefix7", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "prefix6", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "prefix5", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "prefix4", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "prefix3", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "prefix2", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "prefix1", operand: OperandType::InlineNone, size: 1 }),
    Some(OpCode { name: "prefixref", operand: OperandType::InlineNone, size: 1 }),
];

//DOUBLE_BYTE 以 0xFE 开头 第二字节索引的指令
pub static DOUBLE_BYTE: [Option<OpCode>; 256] = [
    Some(OpCode { name: "arglist", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "ceq", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "cgt", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "cgt.un", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "clt", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "clt.un", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "ldftn", operand: OperandType::InlineMethod, size: 2 }),
    Some(OpCode { name: "ldvirtftn", operand: OperandType::InlineMethod, size: 2 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "ldarg", operand: OperandType::InlineVar, size: 2 }),
    Some(OpCode { name: "ldarga", operand: OperandType::InlineVar, size: 2 }),
    Some(OpCode { name: "starg", operand: OperandType::InlineVar, size: 2 }),
    Some(OpCode { name: "ldloc", operand: OperandType::InlineVar, size: 2 }),
    Some(OpCode { name: "ldloca", operand: OperandType::InlineVar, size: 2 }),
    Some(OpCode { name: "stloc", operand: OperandType::InlineVar, size: 2 }),
    Some(OpCode { name: "localloc", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "endfilter", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "unaligned.", operand: OperandType::ShortInlineI, size: 2 }),
    Some(OpCode { name: "volatile.", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "tail.", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "initobj", operand: OperandType::InlineType, size: 2 }),
    Some(OpCode { name: "constrained.", operand: OperandType::InlineType, size: 2 }),
    Some(OpCode { name: "cpblk", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "initblk", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "rethrow", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "sizeof", operand: OperandType::InlineType, size: 2 }),
    Some(OpCode { name: "refanytype", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "readonly.", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 2 }),
    Some(OpCode { name: "unused", operand: OperandType::InlineNone, size: 2 }),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
];
